# Generated by Django 2.1.7 on 2019-03-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlink',
            name='topic',
            field=models.ManyToManyField(null=True, to='core.HashTag'),
        ),
    ]
