# Generated by Django 2.1.7 on 2019-03-18 19:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_link_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
