# Generated by Django 2.1.7 on 2019-03-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_postlink_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlink',
            name='topic',
            field=models.ManyToManyField(to='core.HashTag'),
        ),
    ]
