# Generated by Django 2.1.7 on 2019-03-18 22:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190318_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
