# Generated by Django 2.1.7 on 2019-03-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190318_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
