# Generated by Django 2.1.7 on 2019-03-19 00:59

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_link_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='link_post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='link_post',
            name='comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(to='core.PostLink'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post',
            field=models.ManyToManyField(to='core.PostLink'),
        ),
        migrations.DeleteModel(
            name='Link_Post',
        ),
        migrations.AddField(
            model_name='postlink',
            name='comments',
            field=models.ManyToManyField(to='core.Comment'),
        ),
    ]
